stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build_services:
  stage: build
  script:
    - docker-compose -f monitoring/docker-compose.yml build
    - docker-compose -f nextcloud/customer1/docker-compose.yml build

deploy_services:
  stage: deploy
  script:
    - docker-compose -f monitoring/docker-compose.yml up -d
    - docker-compose -f nextcloud/customer1/docker-compose.yml up -d
    - apt-get update && apt-get install -y python3 python3-pip
    - pip3 install ansible
    - ansible-playbook zammad/install_zammad.yml -i zammad/inventory.ini
  only:
    - master

verify_services:
  stage: deploy
  script:
    - docker ps
  only:
    - master

cleanup_services:
  stage: deploy
  script:
    - docker-compose -f monitoring/docker-compose.yml down
    - docker-compose -f nextcloud/customer1/docker-compose.yml down
  when: always
