stages:
  - build
  - deploy

build_customer1:
  stage: build
  script:
    - cd nextcloud/customer1
    - docker-compose build

build_customer2:
  stage: build
  script:
    - cd nextcloud/customer2
    - docker-compose build

build_zammad:
  stage: build
  script:
    - cd zammad
    - docker-compose build

build_monitoring:
  stage: build
  script:
    - cd monitoring
    - docker-compose build

deploy_customer1:
  stage: deploy
  script:
    - cd nextcloud/customer1
    - docker-compose up -d

deploy_customer2:
  stage: deploy
  script:
    - cd nextcloud/customer2
    - docker-compose up -d

deploy_zammad:
  stage: deploy
  script:
    - cd zammad
    - docker-compose up -d

deploy_monitoring:
  stage: deploy
  script:
    - cd monitoring
    - docker-compose up -d
