stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apt-get update
  - apt-get install -y curl
  - curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

build_monitoring:
  stage: build
  script:
    - echo "Moving to the Monitoring directory..."
    - cd Monitoring
    - echo "Listing contents of the Monitoring directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

build_customer1:
  stage: build
  script:
    - cd nextcloud/customer1
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

build_customer2:
  stage: build
  script:
    - cd nextcloud/customer2
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

build_zammad:
  stage: build
  script:
    - cd zammad
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

deploy_customer1:
  stage: deploy
  script:
    - cd nextcloud/customer1
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi

deploy_customer2:
  stage: deploy
  script:
    - cd nextcloud/customer2
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi

deploy_monitoring:
  stage: deploy
  script:
    - cd Monitoring
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi

deploy_zammad:
  stage: deploy
  script:
    - cd zammad
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi
