stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"  # Ensure Docker daemon uses TLS (security)

services:
  - name: docker:20.10.16-dind
    alias: docker
    command: ["--mtu=1500"]

before_script:
  - docker info  # To check if Docker is running and configured
  - apk update && apk add --no-cache curl docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

build_monitoring:
  stage: build
  script:
    - echo "Moving to the Monitoring directory..."
    - cd Monitoring
    - echo "Listing contents of the Monitoring directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build..."
        docker-compose build
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build."
        exit 1
      fi

build_customer1:
  stage: build
  script:
    - cd nextcloud/customer1
    - echo "Listing contents of the Customer1 directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build..."
        docker-compose build
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build."
        exit 1
      fi

build_customer2:
  stage: build
  script:
    - cd nextcloud/customer2
    - echo "Listing contents of the Customer2 directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build..."
        docker-compose build
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build."
        exit 1
      fi

deploy_customer1:
  stage: deploy
  script:
    - cd nextcloud/customer1
    - echo "Listing contents of the Customer1 directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment..."
        docker-compose up -d
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment."
        exit 1
      fi

deploy_customer2:
  stage: deploy
  script:
    - cd nextcloud/customer2
    - echo "Listing contents of the Customer2 directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment..."
        docker-compose up -d
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment."
        exit 1
      fi

deploy_monitoring:
  stage: deploy
  script:
    - cd Monitoring
    - echo "Listing contents of the Monitoring directory..."
    - ls -la
    - if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment..."
        docker-compose up -d
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment."
        exit 1
      fi

deploy_zammad:
  stage: deploy
  script:
    - echo "Moving to the Zammad directory..."
    - cd zammad
    - echo "Running Ansible playbook for Zammad..."
    - ansible-playbook -i inventory.ini install_zammad.yml
