stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose  # Ensuring docker-compose is available
  - docker info

build:
  stage: build
  script:
    - docker-compose -f docker-compose.nextcloud.yml build
    - docker-compose -f docker-compose.zammad.yml build
  only:
    - main

test:
  stage: test
  script:
    - docker-compose -f docker-compose.nextcloud.yml up -d
    - docker-compose -f docker-compose.zammad.yml up -d
    - sleep 60 # Optionally, replace with health checks
    - docker-compose -f docker-compose.nextcloud.yml ps
    - docker-compose -f docker-compose.zammad.yml ps
    - echo "Tests complete."
  only:
    - main
  after_script:
    - docker-compose -f docker-compose.nextcloud.yml down
    - docker-compose -f docker-compose.zammad.yml down

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - docker-compose -f docker-compose.nextcloud.yml up -d
    - docker-compose -f docker-compose.zammad.yml up -d
  environment:
    name: production
  only:
    - main
  when: manual
