stages:
  - build
  - deploy
  - test
  - cleanup

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build_services:
  stage: build
  image: docker:latest
  script:
    - echo "Building Monitoring services..."
    - docker-compose -f monitoring/docker-compose.yml build
    - echo "Building Nextcloud services..."
    - docker-compose -f nextcloud/customer1/docker-compose.yml build
  allow_failure: false
  only:
    - main

deploy_services:
  stage: deploy
  image: docker:latest
  script:
    - echo "Deploying Monitoring services..."
    - docker-compose -f monitoring/docker-compose.yml up -d
    - echo "Deploying Nextcloud services..."
    - docker-compose -f nextcloud/customer1/docker-compose.yml up -d
    - echo "Deploying Zammad..."
    - apt-get update && apt-get install -y ansible
    - ansible-playbook -i zammad/inventory.ini zammad/install_zammad.yml
  allow_failure: false
  only:
    - main

test_services:
  stage: test
  image: docker:latest
  script:
    - echo "Running smoke tests..."
    - curl -f http://localhost:9090
    - curl -f http://localhost:3000
    - curl -f http://localhost:8060
  allow_failure: true
  only:
    - main

cleanup_services:
  stage: cleanup
  image: docker:latest
  script:
    - echo "Cleaning up services..."
    - docker-compose -f monitoring/docker-compose.yml down
    - docker-compose -f nextcloud/customer1/docker-compose.yml down
  when: always
  only:
    - main
