stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apt-get update
  - apt-get install -y curl apt-transport-https ca-certificates gnupg2 software-properties-common
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - service docker start
  - sleep 20 # Wait for Docker to initialize
  - docker info # Verify Docker is running

build_monitoring:
  stage: build
  script:
    - echo "Moving to the Monitoring directory..."
    - cd Monitoring
    - echo "Listing contents of the Monitoring directory..."
    - ls -la
    - |
      if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

build_customer1:
  stage: build
  script:
    - echo "Moving to the Customer1 directory..."
    - cd nextcloud/customer1
    - echo "Listing contents of the Customer1 directory..."
    - ls -la
    - |
      if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

build_customer2:
  stage: build
  script:
    - echo "Moving to the Customer2 directory..."
    - cd nextcloud/customer2
    - echo "Listing contents of the Customer2 directory..."
    - ls -la
    - |
      if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting build...";
        docker-compose build;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with build.";
        exit 1;
      fi

build_zammad:
  stage: build
  script:
    - echo "Moving to the Zammad directory..."
    - cd zammad
    - echo "Listing contents of the Zammad directory..."
    - ls -la
    - |
      if [ -f "install_zammad.yml" ]; then
        echo "install_zammad.yml found, skipping build step since it's an Ansible playbook.";
      else
        echo "install_zammad.yml not found in $(pwd), cannot proceed.";
        exit 1;
      fi

deploy_customer1:
  stage: deploy
  script:
    - echo "Moving to the Customer1 directory..."
    - cd nextcloud/customer1
    - echo "Listing contents of the Customer1 directory..."
    - ls -la
    - |
      if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi

deploy_customer2:
  stage: deploy
  script:
    - echo "Moving to the Customer2 directory..."
    - cd nextcloud/customer2
    - echo "Listing contents of the Customer2 directory..."
    - ls -la
    - |
      if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi

deploy_monitoring:
  stage: deploy
  script:
    - echo "Moving to the Monitoring directory..."
    - cd Monitoring
    - echo "Listing contents of the Monitoring directory..."
    - ls -la
    - |
      if [ -f "docker-compose.yml" ]; then
        echo "docker-compose.yml found, starting deployment...";
        docker-compose up -d;
      else
        echo "docker-compose.yml not found in $(pwd), cannot proceed with deployment.";
        exit 1;
      fi

deploy_zammad:
  stage: deploy
  script:
    - echo "Moving to the Zammad directory..."
    - cd zammad
    - echo "Running Ansible playbook for Zammad..."
    - ansible-playbook -i inventory.ini install_zammad.yml
