stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y curl
  - curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

build_customer1:
  stage: build
  script:
    - cd nextcloud/customer1
    - docker-compose build

build_customer2:
  stage: build
  script:
    - cd nextcloud/customer2
    - docker-compose build

build_zammad:
  stage: build
  script:
    - cd zammad
    - docker-compose build

build_monitoring:
  stage: build
  script:
    - cd monitoring
    - docker-compose build

deploy_customer1:
  stage: deploy
  script:
    - cd nextcloud/customer1
    - docker-compose up -d

deploy_customer2:
  stage: deploy
  script:
    - cd nextcloud/customer2
    - docker-compose up -d

deploy_zammad:
  stage: deploy
  script:
    - cd zammad
    - docker-compose up -d

deploy_monitoring:
  stage: deploy
  script:
    - cd monitoring
    - docker-compose up -d
