stages:
  - setup
  - deploy

setup:
  stage: setup
  script:
    - apt-get update -y
    - apt-get install -y docker.io docker-compose
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - main
  tags:
    - docker
