global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nextcloud'
    static_configs:
      - targets: ['customer1:8080', 'customer2:8080']

  - job_name: 'zammad'
    static_configs:
      - targets: ['zammad:3000']
